=== tecweb/progetto/xml/schema/soluzione.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="soluzione">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="proposta" type="xs:string"/>
        <xs:element name="pro" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="contro" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="domanda" type="Tdom" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Tdom">
    <xs:sequence>
      <xs:element name="testo" type="xs:string"/>
			<xs:element name="opzione" type="Topz" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
	<xs:complexType name=Topz>
		<xs:sequence>
			<xs:element name="descrizione" type="xs:string"/>
			<xs:element name="nvoti" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== tecweb/progetto/public_html/tematiche/lampioni LED/sol_led.xml
<?xml version="1.0"?>
<soluzione xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="../../../xml/schema/soluzione.xsd">
  <proposta> Sostituire le lampade dei lampioni con lampade LED man mano che le vecchie lampade si bruciano. </proposta>
<pro> Le lampade a LED consumano meno energia elettrica (mediamente il 50% delle attuali lampade a vapori di sodio a bassa pressione) </pro>
<pro>Le lampade a LED durano in media 50.000 ore, 5 volte la vita media delle attuali lampade a vapori di sodio a bassa pressione, quindi non serve sostituirle ogni 2 anni, ma ogni 10</pro>
<pro>Il basso consumo di queste nuove lampade rende più possibile l'alimentazione con energia elettrica prodotta da impianti fotovoltaici di cui il Comune si potrà dotare nei prossimi anni</pro>
<pro>Il colore della luce è bianco (5500k) permettendo una migliore percezione dei colori</pro>
<pro>Non necessitano di manutenzione poiché non generando calore il vetro rimane freddo e si sporca molto meno</pro>
<pro>Si accendono istantaneamente a pieno regime con qualsiasi temperatura esterna</pro>
<pro>Hanno luce fissa che non sfarfalla</pro>
<contro>il costo delle lampade LED è attualmente molto più alto (10 volte tanto), tuttavia i costi sono in rapido calo e la tecnologia è in continuo sviluppo</contro>

  <domanda>
    <testo>Secondo te è possibile rimuovere le sostanze nocive durante il trattamento di trasformazione in compost?</testo>
    <opzione>
      <descrizione>Sì</descrizione>
      <nvoti>2</nvoti>
    </opzione>
    <opzione>
      <descrizione>No</descrizione>
      <nvoti>6</nvoti>
    </opzione>
    <opzione>
      <descrizione>Forse sì, ma non mi fiderei comunque a utilizzare il compost in agricoltura biologica</descrizione>
      <nvoti>4</nvoti>
    </opzione>
  </domanda>
</soluzione>

=== tecweb/progetto/public_html/tematiche/trasparenza amministrativa/sol_sportello.xml
<?xml version="1.0"?>
<soluzione xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="../../../xml/schema/soluzione.xsd">
  <proposta> Rendere pubbliche tutte le attività degli uffici amministrativi e della Giunta, pubblicandole sul sito Internet del Comune, riassumendole in una pubblicazione cartacea mensile, istituendo uno sportello informativo presso il municipio. In particolare le riunioni della Giunta saranno precedute dalla pubblicazione dell'Ordine del Giorno, trasmesse in videoconferenza accessibile a tutti, registrate e rese sempre disponibili sul sito ufficiale del Comune.
  </proposta>
<pro> Chiunque potrà controllare l'operato dell'amministrazione e segnalare eventuali irregolarità ed errori </pro>
<pro>Gli amministratori, sentendosi controllati, faranno del loro meglio per agire equamente, correttamente, efficientemente</pro>
<pro>La possibilità di informarsi approfonditamente stimolerà l'interesse di alcuni cittadini verso l'attività amministrativa, diffonderà la conoscenza e formerà nuovi potenziali amministratori preparati che garantiranno il ricambio negli anni a venire.</pro>
<pro>Qualora gli amministratori si rifiutassero di aderire a questa proposta si potrebbe legittimamente pensare che stiano operando in mala fede </pro>

<contro>Per gestire il sito e lo sportello sarà necessario impiegare almeno una persona a tempo pieno</contro>
<contro>La pubblicazione cartacea mensile ha un costo di stampa e distribuzione, ma è necessaria perlomeno finché l'uso della rete Internet non si sarà diffuso maggiormente.</contro>

  <domanda>
    <testo>Secondo te è possibile rimuovere le sostanze nocive durante il trattamento di trasformazione in compost?</testo>
    <opzione>
      <descrizione>Sì</descrizione>
      <nvoti>2</nvoti>
    </opzione>
    <opzione>
      <descrizione>No</descrizione>
      <nvoti>6</nvoti>
    </opzione>
    <opzione>
      <descrizione>Forse sì, ma non mi fiderei comunque a utilizzare il compost in agricoltura biologica</descrizione>
      <nvoti>4</nvoti>
    </opzione>
  </domanda>
</soluzione>

=== tecweb/progetto/public_html/tematiche/biomasse/sol_bubarate.xml
<?xml version="1.0"?>
<soluzione xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="../../../xml/schema/soluzione.xsd">
  <proposta> Si fanno delle "bubarate" direttamente sui campi  </proposta>
<pro> sono belli da vedere all'epifania. </pro>
<pro> Abbiamo sempre fatto così, "vuttu farme far che po' ti ades?" </pro>
<contro>La legge (citare quale) non lo permette o presto non lo permetterà</contro>
<contro>contributo negativo alla qualità dell'aria che questi incendi provocano</contro>
<contro>emettendo negli strati più bassi dell'atmosfera quantità elevate di fumi difficilmente disperdibili con le nostre condizioni meteorologiche invernali;</contro>
<contro>i costi di gestione sono maggiori rispetto alla trinciatura.</contro>
<contro>Spreco inutile di materiale energetico.</contro>

  <domanda>
    <testo>Secondo te è possibile rimuovere le sostanze nocive durante il trattamento di trasformazione in compost?</testo>
    <opzione>
      <descrizione>Sì</descrizione>
      <nvoti>2</nvoti>
    </opzione>
    <opzione>
      <descrizione>No</descrizione>
      <nvoti>6</nvoti>
    </opzione>
    <opzione>
      <descrizione>Forse sì, ma non mi fiderei comunque a utilizzare il compost in agricoltura biologica</descrizione>
      <nvoti>4</nvoti>
    </opzione>
  </domanda>
</soluzione>

=== tecweb/progetto/public_html/tematiche/Wi-Fi comunale/wifi.xml
<?xml version="1.0"?>
<soluzione xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="../../../xml/schema/soluzione.xsd">
	<proposta> Costruire alcuni punti di accesso Wi-Fi (cioè via radio) in luoghi strategici. La rete rimarrà di proprietà del Comune che fornirà il servizio ad un costo molto basso ai privati e alle aziende, e gratuitamente a scuole, edifici amministrativi, carabinieri, ecc. </proposta>
  <pro> La connessione a banda larga sarà disponibile anche per gli utenti che loro malgrado non sono raggiunti da servizi privati </pro>
  <pro> Il costo per tutte le famiglie e le aziende sarà più che dimezzato rispetto alle attuali tariffe subite da chi è già raggiunto dal servizio privato </pro>
	<pro>Sarà possibile telefonare gratuitamente all'interno del territorio comunale arrtraverso la tecnologia VOIP, realizzando così un risparmio per l'amministrazione e per i cittadini che utilizzeranno questo servizio</pro>
	<pro>Si favorirà la partecipazione pubblica alle attività di amministrazione ed al controllo sull'operato degli amministratori</pro>
	<pro> Si potranno strutturare in maniera semplice e a costi limitati, servizi di videosorveglianza</pro>
	<pro> L'installazione dell'intera rete e dei punti di accesso non comporta grosse opere pubbliche nè disagi alla viabilità, e si prevedono tempi molto brevi per l'installazione e la messa in servizio, e anche per la riparazione di eventuali guasti</pro>
	<pro> Ridotto impatto ambientale sia elettromagnetico che paesaggistico (niente tralicci, dimensioni limitate delle antenne - paragonabili ad una parabola per la TV)</pro>
	<pro> Possibilità di creare servizi per il turismo, percorsi guidati su palmari e videotelefoni, guide per scoprire in modo approfondito il territorio muovendosi al suo interno</pro>
	<pro> Migliorare la qualità ed i tempi di erogazione di alcuni servizi pubblici</pro>
<contro> Il territorio valdobbiadenese è complesso, così come complessa sarà la scelta di dove posizionare i punti di accesso wi-fi, cioè le piccole antenne che trasmetteranno e riceverrano il segnale</contro>
<contro> Le reali possibilità di finanziare le spese correnti (cioè la gestione annuale del servizio) con il solo canone fisso non possono essere previste con calcoli certi, poiché dipendenti dal numero di abbonati al servizio.</contro>
<contro> L'installazione della rete potrebbe costare intorno ai 150.000euro e avere un costo di manutenzione intorno ai 30.000euro annui (Fonte Comune di Soveria Mannelli (CZ))</contro>
<contro> Le antenne potrebbero subire danni a causa di condizioni meteo o atti vandalici</contro>
  <domanda>
    <testo> Pensi che usufruirai di questo servizio? </testo>
    <opzione>
      <descrizione> Sì </descrizione>
      <nvoti> 0 </nvoti>
    </opzione>
    <opzione>
      <descrizione> No </descrizione>
      <nvoti> 0 </nvoti>
    </opzione>
    <opzione>
      <descrizione> Non lo so </descrizione>
      <nvoti> 0 </nvoti>
    </opzione>
  </domanda>
	<domanda>
    <testo>Colore preferito?</testo>
    <opzione>
      <descrizione> Giallo </descrizione>
      <nvoti>7</nvoti>
    </opzione>
    <opzione>
      <descrizione> Blu </descrizione>
      <nvoti> 3 </nvoti>
    </opzione>
    <opzione>
      <descrizione> Rosso </descrizione>
      <nvoti> 0 </nvoti>
    </opzione>
  </domanda>
</soluzione>

=== tecweb/progetto/public_html/tematiche/biomasse/sol_centrale_elettrica.xml
<?xml version="1.0"?>
<soluzione xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="../../../xml/schema/soluzione.xsd">
  <proposta> Raccogliere i sarmenti in campo con trincia-raccogli-caricatrici, vendere il cippato prodotto ad una centrale per la produzione di energia elettrica alimentata a biomassa.</proposta>
<pro>I sarmenti verrebbero allontanati dal vigneto evitando ogni possibile contaminazione da parte di malattie funginee.</pro>
<pro>Per il territorio e per le aziende sarebbe un valore aggiunto, nell'ottica del marketing territoriale, poter affermare che si utilizzano le biomasse per produrre energia elettrica .</pro>
<pro>Le sostanze inquinanti con cui si effettuano i trattamenti delle viti (Dimetomorf, Iprovalicarb, Bentiavalicarb, Fenamidone, Metalaxil, Benalaxil, Fosetil di alluminio, Mancozeb, Metifam, Folpet, Rame (idrossido/ossicloruro/solfato), Zolfo, Quinoxyfen, Metrafenone, Spiroxamina, Meptyldinocap, Proquinazid, Bupirimate, Flufenoxuron,  Buprofezin, Indoxacarb, Clorpirifos etile/metile, Malathion, Etofenprox, Thiamethoxam, Ciprodinil, Fludioxonil, Fenexamide, Mepanipyrim, Pyrimetanil, Boscalid, Cyazofamid, Pyraclostrobin, Azoxistrobin, Zoxamide, Clofentezine, Dicofol, Dicofol + Exitiazox, Exitiazox, Etoxazole, Fenazaquin, Exitiazox + Fenazaquin, Fenpiroximate, Propargite, Pyridaben, Spirodiclofen, Tebufenpirad. Fonte: bollettini CO.DI.TV) non verrebbero ulteriormente diffuse nel territorio comunale visto che non ci sarebbero più combustioni all'aria aperta senza filtri, (per esempio la combustione del solo Mancozeb libera acido cianidrico, monossido di carbonio, diossido di zolfo e ossido di azoto).</pro>
<pro>I fumi prodotti dalle sostanze inquinanti con cui si effettuano i trattamenti delle viti verrebbero assorbiti da particolari filtri (particolarmente onerosi quindi giustificati economicamente da impianti di una certa dimensione) evitandone così la dispersione in atmosfera.</pro>   
<pro>Eventuale creazione di posti di lavoro per la raccolta ed il trasporto della biomassa.</pro>
<pro>Creazione di una filiera virtuosa che recuperi ciò che convenzionalmente viene considerato scarto e lo "trasformi" in risorsa rientrando nelle logiche di convenienza economica. </pro>
<contro>E' necessario trasportare i tralci e sminuzzarli</contro>
<contro>La scienza non è certa che la centrale a biomassa sia pulita e non produca nanoparticelle che inquineranno per sempre le zone vicine alla centrale dove verranno combuste.</contro>
<contro>È indispensabile creare una complessa rete organizzativa che coinvolga gli agricoltori, i rappresentanti di categoria, il consorzio di tutela, le ditte di trasporto e la centrale.</contro>
  <domanda>
    <testo>Ritieni realizzabile questa soluzione?</testo>
    <opzione>
      <descrizione> Sì </descrizione>
      <nvoti>7</nvoti>
    </opzione>
    <opzione>
      <descrizione> No </descrizione>
      <nvoti> 3 </nvoti>
    </opzione>
    <opzione>
      <descrizione> Non lo so </descrizione>
      <nvoti> 0 </nvoti>
    </opzione>
  </domanda>
	<domanda>
    <testo>Ritieni che sia una soluzione economicamente sostenibile?</testo>
    <opzione>
      <descrizione> Sì </descrizione>
      <nvoti>7</nvoti>
    </opzione>
    <opzione>
      <descrizione> No </descrizione>
      <nvoti> 3 </nvoti>
    </opzione>
    <opzione>
      <descrizione> Non so </descrizione>
      <nvoti> 0 </nvoti>
    </opzione>
  </domanda>
	<domanda>
    <testo>Ritieni che ci possa essere del vantaggio economico dall'adozione di questa soluzione?</testo>
    <opzione>
      <descrizione> Sì </descrizione>
      <nvoti>7</nvoti>
    </opzione>
    <opzione>
      <descrizione> No </descrizione>
      <nvoti> 3 </nvoti>
    </opzione>
    <opzione>
      <descrizione> Non so </descrizione>
      <nvoti> 0 </nvoti>
    </opzione>
  </domanda>
	<domanda>
    <testo>Sei interessato ad approfondire questa soluzione? (anche attraerso degli incontri)</testo>
    <opzione>
      <descrizione> Sì </descrizione>
      <nvoti>7</nvoti>
    </opzione>
    <opzione>
      <descrizione> No </descrizione>
      <nvoti> 3 </nvoti>
    </opzione>
    <opzione>
      <descrizione> Non so </descrizione>
      <nvoti> 0 </nvoti>
    </opzione>
  </domanda>
</soluzione>

=== tecweb/progetto/public_html/tematiche/biomasse/sol_interfilare.xml
<?xml version="1.0"?>
<soluzione xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="../../../xml/schema/soluzione.xsd">
  <proposta> Si tritano i sarmenti lasciandoli nell'interfilare. </proposta>
<pro>Questo permette di restituire annualmente al terreno un quantitativo pari a circa il 25% del fabbisogno di sostanza organica (Corradi, 2006);
</pro>
<pro>Rapidità ed economicità dell'intervento, soprattutto se fatto in concomitanza con il primo sfalcio dell'erba, si fanno così due operazioni con una passata.</pro>
<contro>necessità di attrezzi adatti (trincia a martelli e non a coltelli) e trattrici abbastanza potenti.</contro>
<contro>È opinione comune che non distruggere il legno di potatura e non asportarlo dal vigneto comporti un aumento dell'inoculo delle malattie della vite (soprattutto mal dell'esca);</contro>
<contro>dalle nostre parti i sarmenti trinciati non potrebbero essere interrati e, rimanendo in superficie, l'apporto in sostanza organica sarebbe molto minore, inoltre la degradazione della lignina richiede un certo consumo di azoto;</contro>
<contro>l'humificazione sarebbe più lenta e incompleta rispetto all'ipotesi 2.</contro>
  <domanda>
    <testo>Secondo te è possibile rimuovere le sostanze nocive durante il trattamento di trasformazione in compost?</testo>
    <opzione>
      <descrizione>Sì</descrizione>
      <nvoti>2</nvoti>
    </opzione>
    <opzione>
      <descrizione>No</descrizione>
      <nvoti>6</nvoti>
    </opzione>
    <opzione>
      <descrizione>Non lo so</descrizione>
      <nvoti>4</nvoti>
    </opzione>
  </domanda>
	<domanda>
    <testo>Ritieni che il potato macinato nel vigneto favorisca la permanenza di malattie nocive alla vite?</testo>
    <opzione>
      <descrizione>Sì</descrizione>
      <nvoti>2</nvoti>
    </opzione>
    <opzione>
      <descrizione>No</descrizione>
      <nvoti>6</nvoti>
    </opzione>
    <opzione>
      <descrizione>Non lo so</descrizione>
      <nvoti>4</nvoti>
    </opzione>
  </domanda>
</soluzione>

=== tecweb/progetto/public_html/tematiche/comitati di frazione/sol_comitati_frazione.xml
<?xml version="1.0"?>
<soluzione xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="../../../xml/schema/soluzione.xsd">
  <proposta> Istituire dei comitati di frazione aperti a tutti i residenti. I Comitati dovranno analizzare eventuali problemi riguardanti la propria frazione e, una volta individuata e proposta una soluzione attuabile, avranno il diritto di chiederne la presa in esame da parte dell'Amministrazione Comunale. </proposta>
<pro> I cittadini si sentiranno maggiormente parte integrante e decisiva del proprio territorio </pro>
<pro> Controllo capillare del territorio e dei problemi che presenta </pro>
<contro> Potrebbe non essere sufficiente affidare alla sola iniziativa dei cittadini il ruolo di costituire e mantenere in vita tali comitati </contro>
<contro> Potrebbe risultare oneroso per l'Amministrazione dare ascolto a tutte le proposte dei singoli comitati, al punto da  rendere vano il lavoro dei comitati </contro>
  <domanda>
    <testo>Ti sentiresti maggiormente rappresentato con l'introduzione di questo strumento?</testo>
    <opzione>
      <descrizione>Sì</descrizione>
      <nvoti>0</nvoti>
    </opzione>
    <opzione>
      <descrizione>No</descrizione>
      <nvoti>0</nvoti>
    </opzione>
    <opzione>
      <descrizione>Non lo so</descrizione>
      <nvoti>0</nvoti>
    </opzione>
  </domanda>
	<domanda>
    <testo> Saresti disposto a partecipare al comitato della tua frazione?</testo>
    <opzione>
      <descrizione>Sì</descrizione>
      <nvoti>0</nvoti>
    </opzione>
    <opzione>
      <descrizione>No</descrizione>
      <nvoti>0</nvoti>
    </opzione>
    <opzione>
      <descrizione>Non lo so</descrizione>
      <nvoti>0</nvoti>
    </opzione>
  </domanda>
</soluzione>
