=== tecweb/progetto/xml/schema/tematica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="tematica">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="descrizione" type="xs:string"/>
        <xs:element name="commento" type="Tcomm" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="Tcomm">
    <xs:sequence>
      <xs:element name="username" type="xs:string"/>
      <xs:element name="data" type="xs:date"/>
      <xs:element name="voto" type="xs:integer"/>
      <xs:element name="testo" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== tecweb/progetto/public_html/tematiche/Wi-Fi comunale/index.xml
<?xml version="1.0"?>
<tematica xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="../../../xml/schema/tematica.xsd">
  <descrizione>La connessione a banda larga alla rete Internet non e'
disponibile in tutto il territorio. Dov'e disponibile sarebbe meglio abbassare i costi di collegamento.
</descrizione>
<commento><username>admin</username><data>2009-03-15</data><voto>0</voto><nvoti>0</nvoti><testo>&amp;lt;zaa</testo></commento><commento><username>admin</username><data>2009-03-15</data><voto>0</voto><nvoti>0</nvoti><testo>fgkjzydf b</testo></commento><commento><username>admin</username><data>2009-03-15</data><voto>0</voto><nvoti>0</nvoti><testo>&amp;gt;&amp;gt;&amp;gt;&amp;gt;&amp;gt;&amp;gt;&amp;gt;&amp;gt;</testo></commento><commento><username>admin</username><data>2009-03-15</data><voto>0</voto><nvoti>0</nvoti><testo>&amp;lt;</testo></commento></tematica>

=== tecweb/progetto/public_html/tematiche/biomasse/index.xml
<?xml version="1.0"?>
<tematica xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="../../../xml/schema/tematica.xsd">
  <descrizione>I tralci potati dalle viti devono essere smaltiti</descrizione>
  <commento>
    <username>Tizio</username>
    <data>2009-01-27</data>
    <voto>2</voto>
	 <nvoti>10</nvoti>
    <testo>Ci sono aziende che si occupano proprio dello smaltimento delle biomasse e forse sarebbe meglio affidarsi a loro</testo>
  </commento>
  <commento>
    <username>Caio</username>
    <data>2009-02-08</data>
    <voto>3.6</voto>
	 <nvoti>6</nvoti>
    <testo>Mi auguro piu che altro che nessuno si dia al fai da te bruciando per conto suo i tralci</testo>
  </commento>
</tematica>
